# Generated by Django 4.2.6 on 2023-10-16 21:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_security_pkid_alter_security_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergeodata",
            name="user",
            field=models.JSONField(verbose_name=accounts.models.User),
        ),
    ]
