# Generated by Django 4.2.6 on 2023-10-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_usergeodata_user_user_usergeo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="usergeo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.usergeodata"
            ),
        ),
    ]
