# Generated by Django 4.2.6 on 2023-10-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_usergeo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="security",
            name="usergeodata",
        ),
        migrations.AddField(
            model_name="usergeodata",
            name="security",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Holiday",
        ),
        migrations.DeleteModel(
            name="Security",
        ),
    ]
