# Generated by Django 4.2.6 on 2023-10-18 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_usergeo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="usergeo",
        ),
        migrations.AddField(
            model_name="usergeodata",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
