# Generated by Django 4.2.6 on 2023-10-18 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_user_usergeo_usergeodata_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_vpn", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="usergeodata",
            name="security",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.security"
            ),
        ),
    ]
