# Generated by Django 4.2.6 on 2023-10-19 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_holiday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergeodata",
            name="security",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.security"
            ),
        ),
        migrations.AlterField(
            model_name="usergeodata",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
