# Generated by Django 4.2.6 on 2023-10-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_usergeodata_security_alter_usergeodata_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergeodata",
            name="security",
        ),
        migrations.AlterField(
            model_name="holiday",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.usergeodata"
            ),
        ),
        migrations.DeleteModel(
            name="Security",
        ),
    ]
