# Generated by Django 4.2.6 on 2023-10-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_holiday_user_alter_usergeodata_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holiday",
            name="user",
        ),
        migrations.AddField(
            model_name="holiday",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.usergeodata",
            ),
        ),
        migrations.AddField(
            model_name="usergeodata",
            name="related_user_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
