# Generated by Django 4.2.6 on 2023-10-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_remove_holiday_user_holiday_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holiday",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="usergeodata",
            name="related_user_id",
        ),
        migrations.AddField(
            model_name="holiday",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.usergeodata",
            ),
        ),
    ]
