# Generated by Django 4.2.6 on 2023-10-19 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_holiday_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergeodata",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
