# Generated by Django 4.2.6 on 2023-10-20 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_usergeodata_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pkid",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
