# Generated by Django 4.2.6 on 2023-10-20 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_remove_user_pkid_alter_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="holiday",
            old_name="user",
            new_name="usergeodata",
        ),
        migrations.AlterField(
            model_name="holiday",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usergeodata",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
