# Generated by Django 4.2.6 on 2023-10-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_rename_user_holiday_usergeodata_alter_holiday_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usergeodata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
